# Generated by Django 3.0 on 2022-07-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('ID', models.IntegerField(max_length=5)),
                ('ESTIPULANTE', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DT_CONTRATO', models.CharField(max_length=20)),
                ('SITUACAO', models.CharField(max_length=20)),
                ('CELULAR', models.CharField(max_length=20)),
            ],
        ),
    ]
