# Generated by Django 3.0 on 2022-07-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wppapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='ID',
        ),
    ]
